name: Release
on:
  release:
    types: [published]
env:
  PROJECT: "github.com/kelindar/talaria"
  GO111MODULE: "on"

jobs:
  publish:
    name: Publish Docker
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go
      - name: Login to DockerHub Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      - name: Build the tagged Docker image
        run: |
          go build .
          docker build . --file Dockerfile --build-arg GO_BINARY=talaria --tag kelindar/talaria:${{steps.vars.outputs.tag}}
      - name: Push the tagged Docker image
        run: docker push kelindar/talaria:${{steps.vars.outputs.tag}}
